    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          echo "Logged into EC2"
          echo "Installing Node.js..."

          if ! command -v nvm &> /dev/null; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          fi

          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install node

          echo "Installing PM2..."
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          REPO_URL="https://github.com/afkzoro/github-aws-ec2.git"
          BRANCH="main"
          REPO_DIR="$HOME/github-aws-ec2"

          if [ -d "$REPO_DIR/.git" ]; then
            cd "$REPO_DIR"
            git pull origin "$BRANCH"
          else
            sudo yum install -y git
            git clone "$REPO_URL" "$REPO_DIR"
          fi

          cd "$REPO_DIR/simple-web-server"
          git pull origin "$BRANCH"
          npm install

          echo "Starting or restarting the application..."
          pm2 restart server.js || pm2 start server.js
        '
